#!/usr/bin/env bash
set -eo pipefail

# -----------------------------------------------------------
# Forked from Foundry.
# https://github.com/foundry-rs/foundry/tree/master/foundryup
# -----------------------------------------------------------

echo "Installing Huff Neo Compiler..."

BASE_DIR="${XDG_CONFIG_HOME:-$HOME}"
HUFF_NEO_DIR="${HUFF_NEO_DIR:-"$BASE_DIR/.huff-neo"}"
HUFF_NEO_BIN_DIR="$HUFF_NEO_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/cakevm/huff-neo/main/hnc-up/hnc-up"
BIN_PATH="$HUFF_NEO_BIN_DIR/hnc-up"

# Create the .foundry bin directory and hnc-up binary if it doesn't exist.
mkdir -p "$HUFF_NEO_BIN_DIR"
curl -sSf -L "$BIN_URL" -o "$BIN_PATH"
chmod +x "$BIN_PATH"

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE="${ZDOTDIR-"$HOME"}/.zshenv"
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "hnc-up: could not detect shell, manually add ${HUFF_NEO_BIN_DIR} to your PATH."
    exit 1
esac

# Only add hnc-up if it isn't already in PATH.
if [[ ":$PATH:" != *":${HUFF_NEO_BIN_DIR}:"* ]]; then
    # Add the hnc-up directory to the path and ensure the old PATH variables remain.
    # If the shell is fish, echo fish_add_path instead of export.
    if [[ "$PREF_SHELL" == "fish" ]]; then
        echo >> "$PROFILE" && echo "fish_add_path -a $HUFF_NEO_BIN_DIR" >> "$PROFILE"
    else
        echo >> "$PROFILE" && echo "export PATH=\"\$PATH:$HUFF_NEO_BIN_DIR\"" >> "$PROFILE"
    fi
fi

echo
echo "Detected your preferred shell is $PREF_SHELL and added hnc-up to PATH."
echo "Run 'source $PROFILE' or start a new terminal session to use hnc-up."
echo "Then, simply run 'hnc-up' to install the Huff Neo Compiler."
